const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../assets/strategy-engine.js');
const X={utils:{sheet_to_json:s=>s.map(r=>r.slice())}};
function fixture(){const w={SheetNames:['MAPA_52_SEMANAS','RESUMO_ESTRATEGIAS','LEIA_ME'],Sheets:{}};w.Sheets.MAPA_52_SEMANAS=[['Equipamento','Plano de manutenção','Item manutenção','Estratégia IP18','Estratégia IP14','Status cruzamento','Ciclos da estratégia','Fora do mapa',...Array.from({length:52},(_,i)=>'S'+String(i+1).padStart(2,'0'))],['AT-01','P1','I1','EST_A','EST_A','OK','MENSAL','',...Array.from({length:52},(_,i)=>i===0?'M / TRI':'')],['AT-01','P2','I2','EST_A','','Não localizado em IP14','MENSAL | BIENAL','BIENAL',...Array.from({length:52},(_,i)=>i===1?'M':'')]];w.Sheets.RESUMO_ESTRATEGIAS=[['Estratégia','Descrição Estratégia','Ciclos'],['EST_A','Exemplo','MENSAL'],['EST_B','Sem vínculo','ANUAL']];w.Sheets.LEIA_ME=[['INFORMAÇÃO','DETALHE'],['Premissa do calendário','Sem data-base de chamada real, início teórico na semana 1.']];return w;}
test('Preserva códigos e cada plano/item, sem gerar datas',()=>{const d=E.parse(fixture(),X);assert.equal(d.rows.length,2);assert.equal(d.rows[0].weeks[0],'M / TRI');assert.equal(d.rows[1].plan,'P2');assert.equal(d.weeks,52);assert.equal(d.theoretical,true);assert.equal(d.rows[0].date,undefined);});
test('Agrupa sem confundir registros, equipamentos e catálogo',()=>{const d=E.parse(fixture(),X),s=E.summarize(d.rows,52);assert.equal(s.assets,1);assert.equal(s.plans,2);assert.equal(s.groups.length,1);assert.equal(d.catalog.length,2);assert.equal(s.pending,1);assert.equal(s.outside,1);assert.deepEqual(s.weekly.slice(0,3),[1,1,0]);});
test('Resumo semanal é derivado dos registros selecionados',()=>{const d=E.parse(fixture(),X),s=E.summarize([d.rows[1]],52);assert.deepEqual(s.weekly.slice(0,2),[0,1]);assert.deepEqual([...s.groups[0].weekSets[1]],['M']);});
test('Semana ausente é rejeitada em vez de deslocar dados',()=>{const w=fixture();w.Sheets.MAPA_52_SEMANAS[0][9]='Outra coluna';assert.throws(()=>E.parse(w,X),/colunas semanais/);});
test('IP14 pode agrupar sem sobrescrever o valor original IP18',()=>{const w=fixture();w.Sheets.MAPA_52_SEMANAS[1][3]='';const d=E.parse(w,X);assert.equal(d.rows[0].strategy,'EST_A');assert.equal(d.rows[0].strategy18,'');});
test('Identificador ausente fica sinalizado e preservado',()=>{const w=fixture();w.Sheets.MAPA_52_SEMANAS[1][0]='';const d=E.parse(w,X);assert.equal(d.rows.length,2);assert.equal(d.issues.length,1);});
